
filePaths = {'/Volumes/buschman/Rodent Data/Behavioral_dynamics_cj/DA017/DA017_041624', ...
             '/Volumes/buschman/Rodent Data/Behavioral_dynamics_cj/DA017/DA017_041824', ...
             '/Volumes/buschman/Rodent Data/Behavioral_dynamics_cj/DA017/DA017_042224', ...
             '/Volumes/buschman/Rodent Data/Behavioral_dynamics_cj/DA017/DA017_042924', ...
             '/Volumes/buschman/Rodent Data/Behavioral_dynamics_cj/DA019/DA019_041924', ...
             '/Volumes/buschman/Rodent Data/Behavioral_dynamics_cj/DA019/DA019_2_042024', ...
             '/Volumes/buschman/Rodent Data/Behavioral_dynamics_cj/DA019/DA019_042224', ...
             '/Volumes/buschman/Rodent Data/Behavioral_dynamics_cj/DA019/DA019_042624'}; 

hitRateC = cell(length(filePaths), 2); 
faRateC = cell(length(filePaths), 2); 

for f = 1:length(filePaths)
    [~, header] = fileparts(filePaths{f}); 
    hitRateC{f, 1} = header; 
    faRateC{f, 1} = header;
    load(fullfile(filePaths{f}, 'Matfiles', strcat(hitRateC{f, 1}, '_LickAnalysis')), 'rez')
    hitRateC{f, 2} = rez.sigD.hitRate;
    faRateC{f, 2} = rez.sigD.FaRate;
end