function [ meta ] = getmetaNidq
%This helper function returns meta data
% using ReadMeta (by Bill Karsh) that can read out the meta file generated by spikeGLX
% ReadMeta requires 1) name of the bin file, 2) file directory of the
% binfile (given as the current file directory - pwd)

fileList = dir('*nidq.meta'); % identify the *.ap.bin file

if length(fileList)==1
    meta = ReadMeta(fileList.name, pwd); % read out the meta file
elseif length(fileList)>1
    error('Make sure there is only one *ap.bin file in the current folder')
elseif isempty(fileList)
    disp('Please specify the directory containing a meta file!')    
    getdir = uigetdir;
    fileList = dir(fullfile(getdir,'*nidq.meta')); % identify the *.ap.bin file
    if length(fileList)==1
        meta = ReadMeta(fileList.name, getdir); % read out the meta file
    elseif length(fileList)>1
        error('Make sure there is only one *ap.bin file in the current folder')
    elseif isempty(fileList)
        error('No meta file was detected!')
    end
end

