%This script loads 1) behavioral timestamps (generated by
% BehaviorTimestamps*.m), and 2) the CSV file containing spike times
% (generated by jrclust), and produces peri-event time histogram and 
% spike raster plot. 

clear all; clear functions; clc

%% Raw voltage traces from bin and meta files
% addpath(genpath('C:\Users\labadmin\Documents\MATLAB'))
% addpath(genpath('C:\Users\labadmin\Documents\MATLAB\SpikeGLX-master 2\MATLAB-SDK')) % the folder with spikeGLX matlab scripts  
% addpath(genpath('C:\Users\labadmin\Documents\MATLAB\TONIC-master'))                 % TONIC-master folder
% addpath(genpath('C:\Users\labadmin\Desktop\jrclust'));                              % jrclust folder

addpath(genpath('/Volumes/RAID2/parkj/MATLAB'))
addpath(genpath('/Users/parkj/Desktop/SpikeGLX-master 2/MATLAB-SDK')) % the folder with spikeGLX matlab scripts  
%addpath(genpath('/Volumes/RAID2/parkj/MATLAB/TONIC-master'))          % TONIC-master folder
%addpath(genpath('/Users/parkj/Desktop/jrclust_user'));               % jrclust folder

%% Load files 
path    = '/Volumes/RAID2/parkj/NeuralData/IT01_Ldms_M1_121317/Matfiles';    % file directory for matfiles 
cd(path)   % change directory to the current data folder

load('imec3Opt1Geometry.mat','geometry') % load the probe geometry
meta = ReadMeta('ITstim_DMSM1_record_121317_g0_t0.imec.ap.bin', '/Volumes/RAID2/parkj/NeuralData/IT01_Ldms_M1_121317/RawData'); % recording meta file 
load('BehVariables', 'ts', 'pos1', 'vel1', 'reach0', 'xpos1', 'ypos1') % load behavioral timestamps (reach start, stop, and position/velocity data for each reach)
csvFileName = 'ITstim_DMSM1_record_121317_g0_t0.imec.ap_imec3_opt3.csv';         % name of the csv file to be read
csvData     = csvread(csvFileName);              % read the csv file (1st col: spike timing, 2nd col: cluster id, 3rd col: max site)
spkClus     = unique(csvData(csvData(:,2)>0,2)); % valid and unique clusters (positive cluster IDs)
%load('ITstim_DMSM1_record_121317_g0_t0.imec.ap_imec3_opt3_jrc.mat','S_clu.csNote_clu') % load manual annotation ('single' or 'multi') 

%% File information
fileInfo       = 'IT01_121317';   % to put the essential file information (animal ID and date of data collection) into the structure for each single units. 
numbSiteProbe  = [384];           % the number of sites per probes
probeDepth     = [4316];          % ventral coordinate (in um) of the dms probe relative to the brain surface 
dvCosConvert   = cos(10/180*pi);  % if probe was angled, probe coordinates need to be corrected 
strCtx         = true;            % boolean to indicate recording from both striatum and cortex on the same axis (true, e.g. imec probe) 
strCtxBorder   = 2000;            % dv relative to the brain surface to be counted as a striatal unit (striatal units should have a dv greater than this)
numbBehSite    = 64;              % the number of NI board sites used for behavioral data collection (default=64)
numbProbe      = unique([length(probeDepth) length(numbSiteProbe)]); % the number of probes used

if length(probeDepth)~=length(numbSiteProbe)
    error('Check the variables; probeDepth & numbChProbe!')
end

% Assign probe identity to channels (as multiple probes might be used)
whichProbe = zeros(sum(numbSiteProbe),1); % probe identity for each channel  

probeId = 1; 
for s = 1:sum(numbSiteProbe)
    if s <= sum(numbSiteProbe(1:probeId))
        whichProbe(s,1) = probeId;
    elseif s > sum(numbSiteProbe(1:probeId))
        whichProbe(s,1) = probeId+1;
        probeId = probeId+1;
    end
end
clearvars probeId s 

%% Process spike times data and generate PSTH and Rasters
% get spike times from the csv file
spkTimes = struct; % the structure to contain spike times
for u = 1:length(spkClus) % for all valid clusters (units)
    clusId = ['c' num2str(spkClus(u))];     % cluster name string
    spkTimes(u).spkTimes = csvData(csvData(:,2)==spkClus(u),1).*1000; % spike times bundled in a structure (in ms, i.e. jrclust data are in seconds)
    spkTimes(u).clusId   = spkClus(u);      % cluster ID
    spkTimes(u).maxSite  = mode(csvData(csvData(:,2)==spkClus(u),3)); % assign the current cluster to a site of the probe
    spkTimes(u).geometry(1) = geometry(spkTimes(u).maxSite,1);        % horizontal geometry
    spkTimes(u).geometry(2) = probeDepth(whichProbe(spkTimes(u).maxSite))-geometry(spkTimes(u).maxSite,2); % vertical geometry
    spkTimes(u).geometry(2) = spkTimes(u).geometry(2).*dvCosConvert;  % corrected dv (original dv multiplied by cosine(probe angle))
    
    if strCtx && strcmp(meta.typeThis, 'imec') % in case recording from both str and ctx using the imec probe
        spkTimes(u).isStr = spkTimes(u).geometry(2) >= strCtxBorder;  % logical for striatum 
    end
    
end
clearvars u 

spkTimesCell    = struct2cell(spkTimes'); % the entire spike times converted into a cell 
if strcmp(meta.typeThis, 'imec')          % in case recording via imec 
    spkTimesCellCTX = spkTimesCell(:,cell2mat(spkTimesCell(5,:))==0); % the CTX spike times cell (1st probe)
    spkTimesCellSTR = spkTimesCell(:,cell2mat(spkTimesCell(5,:))==1); % the STR spike times cell (2nd probe)
elseif strcmp(meta.typeThis, 'nidq')      % in case recording from one or two apig probes
    spkTimesCellCTX = spkTimesCell(:,cell2mat(spkTimesCell(3,:))<=64); % the CTX spike times cell (1st probe)
    spkTimesCellSTR = spkTimesCell(:,cell2mat(spkTimesCell(3,:))>64);  % the STR spike times cell (2nd probe)
end

psthPlotFlag   = false; % boolean - to plot psth or not

% binned spike count CTX reachStart 
binSpkCountCTXReach    = psthBIN( fileInfo, 'M1', spkTimesCellCTX, ts.reachStart', ts.reachStart', 1, [1e3 3e3], -1, psthPlotFlag );       % entire reachStart 
binSpkCountCTXrwd      = psthBIN( fileInfo, 'M1', spkTimesCellCTX, ts.reward', ts.reachStart', 1, [3e3 1e3], -1, psthPlotFlag );           % entire rewardDelivery
binSpkCountCTXstmLaser = psthBIN( fileInfo, 'M1', spkTimesCellCTX, ts.stmLaser', ts.reachStart', 1, [1e3 3e3], -1, psthPlotFlag );         % laser stim trials
binSpkCountCTXtagLaser = psthBIN( fileInfo, 'M1', spkTimesCellCTX, ts.tagLaser', ts.tagLaser', 1, [5e3 5e3], -1, psthPlotFlag );         % laser tag trials
binSpkCountCTXstmReach = psthBIN( fileInfo, 'M1', spkTimesCellCTX, ts.stmReachStart', ts.reachStart', 1, [1e3 3e3], -1, psthPlotFlag ); % reachStart with stimulation (completed reaches even during stimulation)

% binned spike count STR reachStart
binSpkCountSTRReach    = psthBIN( fileInfo, 'DMS', spkTimesCellSTR, ts.reachStart', ts.reachStart', 1, [1e3 3e3], -1, psthPlotFlag );       % entire reachStart 
binSpkCountSTRrwd      = psthBIN( fileInfo, 'DMS', spkTimesCellSTR, ts.reward', ts.reachStart', 1, [3e3 1e3], -1, psthPlotFlag );           % entire rewardDelivery
binSpkCountSTRstmLaser = psthBIN( fileInfo, 'DMS', spkTimesCellSTR, ts.stmLaser', ts.reachStart', 1, [1e3 3e3], -1, psthPlotFlag );         % laser stim trials
binSpkCountSTRtagLaser = psthBIN( fileInfo, 'DMS', spkTimesCellSTR, ts.tagLaser', ts.tagLaser', 1, [5e3 5e3], -1, psthPlotFlag );         % laser tag trials
binSpkCountSTRstmReach = psthBIN( fileInfo, 'DMS', spkTimesCellSTR, ts.stmReachStart', ts.reachStart', 1, [1e3 3e3], -1, psthPlotFlag ); % reachStart with stimulation (completed reaches even during stimulation)

% draw rasters
% figure;
% rasterJP(spkTimesCell, ts.reachStart', 6, 10);   % neural spike data, behavioral event vector, #row, # column of subplots
% rasterJP(spkTimesCell, ts.reward', 6, 10); 
% neural spike data must be provided in a cell array each cell containing the unit's spiketime vector
% behavioral timestamps must be provided as an event time vector(s)

% save files
saveNameCTX = strcat('binSpkCountCTX',fileInfo);
saveNameSTR = strcat('binSpkCountSTR',fileInfo);
save(saveNameCTX, 'binSpkCountCTXReach', 'binSpkCountCTXrwd', 'binSpkCountCTXstmLaser', 'binSpkCountCTXtagLaser', 'binSpkCountCTXstmReach', 'spkTimesCellCTX', 'meta') % save the data
save(saveNameSTR, 'binSpkCountSTRReach', 'binSpkCountSTRrwd', 'binSpkCountSTRstmLaser', 'binSpkCountSTRtagLaser', 'binSpkCountSTRstmReach', 'spkTimesCellSTR', 'meta') % save the data

%% Individual unit raster plot
spikeRasterGramm( [1e3 3e3], {'reach','stimReach'}, binSpkCountCTXReach(11).SpkTimes, binSpkCountCTXstmReach(11).SpkTimes );

unit = 139; % str unit 128 (laser activated)
spikeRasterGramm( [1e3 3e3], {'reach','stim','stimReach'}, binSpkCountSTRReach(unit).SpkTimes, binSpkCountSTRstmLaser(unit).SpkTimes,binSpkCountSTRstmReach(unit).SpkTimes );





