function p = parse_input_PP( filePath, vargs )
% Updated on 8/22/24 for the new rig at PNI284
% parse input, and extract name-value pairs
default_reReadBin = false; % by default do not re-read the raw bin file, if done already
default_numbNeuralProbe = 0;  % specify how many NIboard probes were used (e.g. zero if no NI neural probe was used)
default_numbChEachProbe = 64; % specify how many channels are on the probe
default_cmosTrigCh   = 1;    % ai0: CMOS trigger
default_faceCamCh    = 2;    % ai1: faceCam exposure pulses
default_speakerCh    = 3;    % ai2: auditory tones generated by speaker
default_treadMillCh  = 5;    % ai4: treadMill signal 
default_sideGreenCh  = 7;    % ai6: exposure pulse from side green camera
default_topRedExpCh  = 8;    % ai7: exposure pulse from top red camera
default_digitCh      = 9;    % the digital channel is always at the tailend

p = inputParser; % create parser object
addRequired(p,'filePath');
addParameter(p,'reReadBin',default_reReadBin);
addParameter(p,'numbNeuralProbe',default_numbNeuralProbe);
addParameter(p,'numbChEachProbe',default_numbChEachProbe);
addParameter(p,'cmosTrigCh',default_cmosTrigCh);
addParameter(p,'faceCamCh',default_faceCamCh);
addParameter(p,'speakerCh',default_speakerCh);
addParameter(p,'treadMillCh',default_treadMillCh);
addParameter(p,'digitCh',default_digitCh);
addParameter(p,'sideGreenCh',default_sideGreenCh)
addParameter(p,'topRedCh',default_topRedExpCh)

parse(p,filePath,vargs{:})
end